CODE_EXTENSIONS_SPECIFIC_LANGUAGE = {
    "JAVA": "*.java",
    "Python": "*.py",
    "C++": "*.cpp"
}

FORMULAE_LOGGING_STATEMENTS_SPECIFIC_LANGUAGE = {
    "JAVA": ["LOG.info("],
}

LINE_TERMINATOR_SPECIFIC_LANGUAGE = {
    "JAVA": ";\n",
}

RUNTIME_LOG_FILE_EXTENSION = "*.log"